# Generated by Django 4.2.21 on 2025-07-31 16:46

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('poster', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('cast', models.TextField(help_text='Comma-separated list of actors')),
                ('release_date', models.DateField()),
                ('duration', models.PositiveIntegerField(help_text='Total duration in minutes')),
                ('is_popular', models.BooleanField(default=False)),
                ('is_coming_soon', models.BooleanField(default=False)),
                ('is_family', models.BooleanField(default=False)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.genre')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
