# Generated by Django 4.2.21 on 2025-08-11 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('repeat_every_days', models.PositiveIntegerField(default=0, help_text='Repeat every N days, 0 means no repeat')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='films.film')),
            ],
        ),
    ]
