# Generated by Django 4.2.21 on 2025-09-11 10:08

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowtimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='film',
            name='hero_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Optional Hero Image for carousel', max_length=255, null=True, verbose_name='Hero Image'),
        ),
        migrations.AddField(
            model_name='film',
            name='is_hero_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='Poster Image'),
        ),
        migrations.CreateModel(
            name='FilmSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_of_week', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True)),
                ('specific_date', models.DateField(blank=True, null=True)),
                ('specific_time', models.TimeField(blank=True, null=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='films.film')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='films.showtimeslot')),
            ],
        ),
        migrations.AddConstraint(
            model_name='filmschedule',
            constraint=models.UniqueConstraint(fields=('film', 'days_of_week', 'slot'), name='unique_film_weekly_schedule'),
        ),
        migrations.AddConstraint(
            model_name='filmschedule',
            constraint=models.UniqueConstraint(fields=('film', 'specific_date', 'specific_time'), name='unique_film_specific_schedule'),
        ),
    ]
