# Generated by Django 4.2.21 on 2025-08-11 10:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_filmschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowtimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='filmschedule',
            name='show_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='filmschedule',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='films.showtimeslot'),
        ),
        migrations.AlterUniqueTogether(
            name='filmschedule',
            unique_together={('show_date', 'slot')},
        ),
        migrations.RemoveField(
            model_name='filmschedule',
            name='repeat_every_days',
        ),
        migrations.RemoveField(
            model_name='filmschedule',
            name='start_datetime',
        ),
    ]
