# Generated by Django 4.2.21 on 2025-08-11 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_showtimeslot_filmschedule_show_date_and_more'),
        ('films', '0004_auto_20250811_1129'),
    ]

    operations = [
    ]
