# Generated by Django 4.2.21 on 2025-08-12 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_merge_20250811_1132'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filmschedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='filmschedule',
            name='days_of_week',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday')], default=0),
        ),
        migrations.AlterField(
            model_name='filmschedule',
            name='slot',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='films.showtimeslot'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='showtimeslot',
            name='start_time',
            field=models.TimeField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='filmschedule',
            unique_together={('days_of_week', 'slot')},
        ),
        migrations.RemoveField(
            model_name='filmschedule',
            name='show_date',
        ),
    ]
