# Generated by Django 4.2.21 on 2025-08-13 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_alter_filmschedule_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filmschedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='filmschedule',
            name='specific_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filmschedule',
            name='specific_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filmschedule',
            name='days_of_week',
            field=models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True),
        ),
        migrations.AlterField(
            model_name='filmschedule',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='films.showtimeslot'),
        ),
        migrations.AlterUniqueTogether(
            name='filmschedule',
            unique_together={('film', 'days_of_week', 'slot', 'specific_date', 'specific_time')},
        ),
    ]
