# Generated by Django 4.2.21 on 2025-08-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_alter_filmschedule_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='is_hero_image',
            field=models.BooleanField(default=False),
        ),
    ]
