# Generated by Django 4.2.21 on 2025-08-28 23:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0008_film_is_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='hero_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Optional Hero Image for carousel', max_length=255, null=True, verbose_name='image'),
        ),
    ]
