# Generated by Django 4.2.21 on 2025-08-28 23:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_film_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='hero_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Optional Hero Image for carousel', max_length=255, null=True, verbose_name='Hero Image'),
        ),
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='Poster Image'),
        ),
    ]
