# Generated by Django 4.2.21 on 2025-09-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0010_alter_film_hero_image_alter_film_poster'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='filmschedule',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='filmschedule',
            constraint=models.UniqueConstraint(fields=('film', 'days_of_week', 'slot'), name='unique_film_weekly_schedule'),
        ),
        migrations.AddConstraint(
            model_name='filmschedule',
            constraint=models.UniqueConstraint(fields=('film', 'specific_date', 'specific_time'), name='unique_film_specific_schedule'),
        ),
    ]
