# Generated by Django 4.2.21 on 2025-09-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0011_alter_filmschedule_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='is_coming_soon',
            field=models.BooleanField(default=False, help_text='Mark this if the film is coming soon.'),
        ),
        migrations.AlterField(
            model_name='film',
            name='is_family',
            field=models.BooleanField(default=False, help_text='Mark this if the film is family friendly.'),
        ),
        migrations.AlterField(
            model_name='film',
            name='is_popular',
            field=models.BooleanField(default=False, help_text='Mark this if the film is popular so it will be on home page.'),
        ),
    ]
