# Generated by Django 4.2.21 on 2025-09-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0012_alter_film_is_coming_soon_alter_film_is_family_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='is_coming_soon',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='film',
            name='is_family',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='film',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
