# Generated by Django 4.2.21 on 2025-08-06 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_popularfilm_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='popularfilm',
            name='description',
        ),
        migrations.RemoveField(
            model_name='popularfilm',
            name='image',
        ),
        migrations.RemoveField(
            model_name='popularfilm',
            name='title',
        ),
    ]
