# Generated by Django 4.2.21 on 2025-08-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_popularfilm_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommingSoon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
