# Generated by Django 4.2.21 on 2025-08-12 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
    ]
