# Generated by Django 4.2.21 on 2025-08-11 11:37

import bookings.seats
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seat_number',
            field=models.CharField(max_length=5, validators=[bookings.seats.validate_seat]),
        ),
    ]
