# Generated by Django 4.2.21 on 2025-08-12 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_merge_20250811_1132'),
        ('bookings', '0002_add_schedule_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='films.showtimeslot'),
        ),
    ]
