# Generated by Django 4.2.21 on 2025-08-11 01:35

import bookings.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('films', '0001_initial'),
        ('bookings', '0002_remove_booking_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['date', 'user']},
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, validators=[bookings.models.validate_not_past_date]),
        ),
        migrations.AddField(
            model_name='booking',
            name='date_booked',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='film',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='films.film'),
        ),
        migrations.AddField(
            model_name='booking',
            name='guests',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.CharField(choices=[('10am', '10am'), ('11am', '11am'), ('12pm', '12pm'), ('1pm', '1pm'), ('2pm', '2pm'), ('3pm', '3pm'), ('4pm', '4pm'), ('5pm', '5pm'), ('6pm', '6pm'), ('7pm', '7pm'), ('8pm', '8pm'), ('9pm', '9pm'), ('10pm', '10pm'), ('11pm', '11pm')], default='10am', max_length=5),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
