# Generated by Django 4.2.21 on 2025-08-11 11:38

import bookings.seats
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_seat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seat_number',
            field=models.CharField(max_length=10, validators=[bookings.seats.validate_seat]),
        ),
    ]
