# Generated by Django 4.2.21 on 2025-08-12 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_alter_filmschedule_unique_together_and_more'),
        ('bookings', '0003_alter_booking_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='films.filmschedule'),
        ),
    ]
