# Generated by Django 4.2.21 on 2025-08-11 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_bookingseat_number_alter_bookingseat_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingseat',
            name='row',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=2),
        ),
    ]
