# Generated by Django 4.2.21 on 2025-08-11 03:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_bookingseat_row'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingseat',
            name='number',
            field=models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
    ]
